#!/bin/bash


_go2_completions()
{

	if [ "${#COMP_WORDS[@]}" != 2 ]
	then
		return
	fi

	local suggestions=($(compgen -W "$(cat ~/.config/nickname/nickname.conf | cut -d',' -f1)" -- "${COMP_WORDS[1]}"))

	if [ "${#suggestions[@]}" == "1" ]
	then
		local word=$(echo ${suggestions[0]/%\ */})
		COMPREPLY=("word")
	else
		COMPREPLY=("${suggestions[@]}")
	fi


}

complete -F _go2_completions go2
