#!/bin/bash


_go2_completions()
{
	local cur="${COMP_WORDS[COMP_CWORD]}"

	# Catch the Options, that accept no params
	if [ "$cur" == "-h" -o "$cur" == "-p" ]
	then
		return
	fi

	# Do if we only have one word, that is a nickname
	if [ "${#COMP_WORDS[@]}" == 2 ]
	then
		if [ -e ~/.config/nickname/nickname.conf ]
		then
			local pos=("$(cat ~/.config/nickname/nickname.conf | cut -d',' -f1)")
			local suggestions=($(compgen -W "${pos} -n -h -p" -- "${COMP_WORDS[1]}"))
		else
			local suggestion=("")
		fi



		if [ "${#suggestions[@]}" == "1" ]
		then
			local word=$(echo ${suggestions[0]/%\ */})
			COMPREPLY=("$word")
		else
			COMPREPLY=("${suggestions[@]}")
		fi	
		
	fi

}

complete -F _go2_completions go2
